services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: matching_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: matching_celery_worker
    env_file:
      - .env
    working_dir: /app
    command: celery -A app.celery_app worker --beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
      - db

  db:
    image: postgres:15
    container_name: matching_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_salesmail:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: matching_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build:
      context: ./frontend
    container_name: matching_frontend
    user: "1000:1000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  postgres_data_salesmail:
  redis_data:
