"""alternate table emails

Revision ID: 2b5bd9850e24
Revises: 0e4cda0fce6e
Create Date: 2025-12-09 09:17:36.384088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5bd9850e24'
down_revision: Union[str, Sequence[str], None] = '0e4cda0fce6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('email_attachments_email_id_fkey'), 'email_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'email_attachments', 'emails', ['email_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('email_attachments_email_id_fkey'), 'email_attachments', 'emails', ['email_id'], ['id'])
    # ### end Alembic commands ###
