"""add price_min and price_max to emails

Revision ID: 3ef2ce1472d1
Revises: b7ba57ab176c
Create Date: 2025-10-14 02:36:58.579485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ef2ce1472d1'
down_revision: Union[str, Sequence[str], None] = 'b7ba57ab176c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('emails', sa.Column('price_min', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('price_max', sa.Integer(), nullable=True))
    op.drop_column('emails', 'main_skills')
    op.drop_column('emails', 'optional_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('optional_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('main_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('emails', 'price_max')
    op.drop_column('emails', 'price_min')
    op.drop_column('emails', 'skills')
    # ### end Alembic commands ###
