"""create email_sync_status table

Revision ID: ba6e91e8141e
Revises: 3ef2ce1472d1
Create Date: 2025-11-20 05:55:25.610302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba6e91e8141e"
down_revision: Union[str, Sequence[str], None] = "3ef2ce1472d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_sync_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_sync_status_id"), "email_sync_status", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_sync_status_id"), table_name="email_sync_status")
    op.drop_table("email_sync_status")
    # ### end Alembic commands ###
