"""add column email_sync_status table

Revision ID: f4cb4fa0caa0
Revises: ba6e91e8141e
Create Date: 2025-11-20 06:26:30.218437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4cb4fa0caa0'
down_revision: Union[str, Sequence[str], None] = 'ba6e91e8141e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_sync_status', sa.Column('added', sa.Integer(), nullable=True))
    op.add_column('email_sync_status', sa.Column('deleted', sa.Integer(), nullable=True))
    op.add_column('email_sync_status', sa.Column('remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_sync_status', 'remaining')
    op.drop_column('email_sync_status', 'deleted')
    op.drop_column('email_sync_status', 'added')
    # ### end Alembic commands ###
